/**
 * /styleguide — design system + branding showcase
 *
 * Admin-only route, available in ALL environments (incl. production).
 * Gated at the loader level via `requireAdminClerkId()`: signed-out users
 * bounce to /sign-in, non-admins bounce to /. Admins are the dev/seed user
 * (in Vite dev) plus any Clerk id in the `ADMIN_CLERK_IDS` worker var.
 *
 * Shows:
 *   1. The Dutch-treat mascot family with idle / happy / surprised
 *      expression frames and CSS keyframe animations.
 *   2. Three palette proposals side-by-side: candy, warm-bakery, vibrant.
 *      Each is scoped under a `.palette-<name>` wrapper class so the
 *      live tokens in src/styles.css are never touched.
 *
 * Generated by GH issue #186.
 */
import { createFileRoute } from "@tanstack/react-router";
import { useState } from "react";
import { assertAdmin } from "../lib/server/admin";

// ---------------------------------------------------------------------------
// Data
// ---------------------------------------------------------------------------

/**
 * The treat cast. Sourced from docs/design/screens-brand.jsx (`ScreenMascotSheet`).
 * Each treat anchors a place in the world — a unit, a feature, an emotional beat.
 * `accent` is the per-character brand colour pulled straight from the design sheet.
 */
const TREATS = [
  {
    slug: "kroket",
    name: "Kroket",
    eponym: "Kroket — fried snack-bar staple",
    role: "Bakkerij unit lead",
    tagline:
      "Holds down the counter at Bakkerij De Stoeptegel. Patient correction-giver.",
    uses: ["Boss-fight roleplays", "Unit 3 hero", "Snack bar scenes"],
    vocab: ["bestellen", "alstublieft", "afrekenen"],
    accent: "#C4774A",
  },
  {
    slug: "bitterballen",
    name: "Bitterballen",
    eponym: "Bitterballen — bar snack",
    role: "Café-scene chorus",
    tagline: "Always shows up in threes. Knows everyone at the bar.",
    uses: ["Social-proof strip", "Friend invites", "Borrel scenes"],
    vocab: ["proost", "een rondje", "gezellig"],
    accent: "#D4600A",
  },
  {
    slug: "oliebollen",
    name: "Oliebollen",
    eponym: "Oliebollen — New Year's doughnut",
    role: "Streak & celebration",
    tagline: "Comes out for milestones — 7, 30, 100 day streaks.",
    uses: ["Daily quests card", "Streak milestones", "Promotion celebration"],
    vocab: ["gelukkig nieuwjaar", "vuurwerk"],
    accent: "#C28E1A",
  },
  {
    slug: "drop",
    name: "Drop",
    eponym: "Drop — Dutch licorice",
    role: "The bouncer",
    tagline: "Sits next to locked content. Doesn't smile. Means well.",
    uses: ["Locked tiles", "Out-of-hearts state", "Premium gates"],
    vocab: ["zout", "zoet", "kun je raden"],
    accent: "#1A1410",
  },
  {
    slug: "poffertjes",
    name: "Poffertjes",
    eponym: "Poffertjes — mini pancakes",
    role: "Beginner cameo",
    tagline:
      "Soft landing for A1 learners. The mascot you pick if you're new.",
    uses: ["A1 level card", "Profile default", "Tutorial walkthroughs"],
    vocab: ["een beetje", "klein", "lief"],
    accent: "#FF7AA2",
  },
  {
    slug: "frikandel",
    name: "Frikandel",
    eponym: "Frikandel — snackbar sausage",
    role: "Energetic sidekick",
    tagline: "The friend who challenges you to a peer drill at 11pm.",
    uses: ["Peer drills", "Leaderboard fast-movers", "Quick wins"],
    vocab: ["snel", "lekker", "doe maar"],
    accent: "#7A3010",
  },
  {
    slug: "tompouce",
    name: "Tompouce",
    eponym: "Tompouce — fondant pastry",
    role: "Polite-conversation lead",
    tagline: "Pink-frosted. Always says 'alstublieft'.",
    uses: ["Bakkerij window", "Polite-form lessons", "Profile cosmetic"],
    vocab: ["alstublieft", "graag", "mag ik"],
    accent: "#FF7AA2",
  },
  {
    slug: "kaas",
    name: "Kaas",
    eponym: "Kaas — Gouda wedge",
    role: "Market-day veteran",
    tagline: "Lives at the kaaswinkel. Will explain de vs het with patience.",
    uses: ["Op de markt unit", "Grammar drills", "Listening drills"],
    vocab: ["jong", "belegen", "een ons"],
    accent: "#C28E1A",
  },
] as const;

const EXPRESSIONS = ["idle", "happy", "surprised"] as const;
type Expression = (typeof EXPRESSIONS)[number];

const PALETTES = [
  {
    slug: "candy",
    name: "Candy",
    rationale:
      "Vivid pinks, electric purples, citrus yellows. Inspired by Dutch hagelslag and sweet-shop treats. Suits a younger audience or seasonal promotions.",
    swatches: [
      { label: "Brand primary", value: "#FF3E9A" },
      { label: "Brand primary dark", value: "#C4006E" },
      { label: "Brand accent", value: "#7B2FFF" },
      { label: "Paper bg", value: "#FFF5FB" },
      { label: "Good", value: "#2DBE6C" },
      { label: "Bad", value: "#FF2D55" },
    ],
  },
  {
    slug: "warm-bakery",
    name: "Warm Bakery",
    rationale:
      "Terracotta brand colour, dark rye ink, parchment surfaces. Inspired by Dutch bakkerij interiors. Feels trustworthy and nostalgic without being heavy.",
    swatches: [
      { label: "Brand primary", value: "#D4600A" },
      { label: "Brand primary dark", value: "#9E4200" },
      { label: "Brand accent", value: "#5A6E2E" },
      { label: "Paper bg", value: "#FDF6EC" },
      { label: "Good", value: "#4A8A3A" },
      { label: "Bad", value: "#A83030" },
    ],
  },
  {
    slug: "vibrant",
    name: "Vibrant",
    rationale:
      "Electric teal + Dutch orange at maximum saturation. The Duolingo-green equivalent for Lekkertaal. Loud, gamified, fast. Suits a future dark-mode-first variant.",
    swatches: [
      { label: "Brand primary", value: "#FF5500" },
      { label: "Brand primary dark", value: "#CC3A00" },
      { label: "Brand accent", value: "#00A8CC" },
      { label: "Paper bg", value: "#F5FEFF" },
      { label: "Good", value: "#00CC66" },
      { label: "Bad", value: "#FF2244" },
    ],
  },
] as const;

// ---------------------------------------------------------------------------
// Route
// ---------------------------------------------------------------------------

export const Route = createFileRoute("/styleguide")({
  loader: async () => await assertAdmin(),
  component: StyleguidePage,
});

// ---------------------------------------------------------------------------
// Components
// ---------------------------------------------------------------------------

function StyleguidePage() {
  const [activeExpression, setActiveExpression] = useState<Expression>("idle");

  return (
    <main
      style={{
        minHeight: "100vh",
        background: "var(--surface-page)",
        fontFamily: "var(--font-sans)",
        padding: "2rem 1.5rem 4rem",
      }}
    >
      <div style={{ maxWidth: "72rem", margin: "0 auto" }}>
        {/* Header */}
        <header style={{ textAlign: "center", marginBottom: "3rem" }}>
          <h1
            style={{
              fontFamily: "var(--font-display)",
              fontSize: "2.5rem",
              fontWeight: 700,
              margin: 0,
            }}
          >
            <span style={{ color: "var(--color-brand-orange)" }}>Lekker</span>
            <span style={{ color: "var(--color-brand-blue)" }}>taal</span>{" "}
            <span style={{ color: "var(--text-soft)" }}>Styleguide</span>
          </h1>
          <p
            style={{
              marginTop: "0.5rem",
              color: "var(--text-muted)",
              fontSize: "0.9rem",
            }}
          >
            Dev-only. Dutch-treat mascots + palette proposals. GH{" "}
            <a
              href="https://github.com/RonanCodes/lekkertaal/issues/186"
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: "var(--color-brand-blue)" }}
            >
              #186
            </a>
            . Research{" "}
            <a
              href="https://github.com/RonanCodes/lekkertaal/issues/184"
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: "var(--color-brand-blue)" }}
            >
              #184
            </a>
            .
          </p>
        </header>

        {/* Brand cast — the treat family */}
        <Section title="The Lekkertaal cast">
          <p
            style={{
              color: "var(--text-soft)",
              marginBottom: "1.25rem",
              fontSize: "0.9rem",
              maxWidth: "46rem",
              lineHeight: 1.6,
            }}
          >
            One stroopwafel and eight Dutch treats. Each treat anchors a place in
            the world — a unit, a feature, an emotional beat — so users meet them
            in context, not in a parade. Each card shows the three expression
            frames (idle, happy, surprised) plus where the character appears and
            the vocab it brings. Per the design sheet in{" "}
            <code
              style={{
                background: "var(--surface-card-alt)",
                padding: "0.1em 0.3em",
                borderRadius: "0.25rem",
                fontSize: "0.85em",
              }}
            >
              docs/design/screens-brand.jsx
            </code>
            .
          </p>
          <ExpressionPicker active={activeExpression} onChange={setActiveExpression} />
          <div
            data-testid="treat-gallery"
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fill, minmax(280px, 1fr))",
              gap: "1.25rem",
              marginTop: "1.5rem",
            }}
          >
            {TREATS.map((treat) => (
              <CastCard
                key={treat.slug}
                treat={treat}
                activeExpression={activeExpression}
              />
            ))}
          </div>
        </Section>

        {/* Stroop included for style reference */}
        <Section title="Style Reference: Stroop">
          <div
            style={{
              display: "flex",
              gap: "1.5rem",
              flexWrap: "wrap",
              alignItems: "flex-start",
            }}
          >
            <div style={{ textAlign: "center" }}>
              <img
                src="/mascot/stroop-512.png"
                alt="Stroop the stroopwafel — existing mascot"
                style={{
                  width: 128,
                  height: 128,
                  objectFit: "contain",
                  borderRadius: "var(--radius-card)",
                  background: "white",
                  padding: "0.5rem",
                  border: "1px solid var(--line-soft)",
                }}
              />
              <p
                style={{
                  marginTop: "0.5rem",
                  fontSize: "0.8rem",
                  color: "var(--text-muted)",
                }}
              >
                Stroop (existing)
              </p>
            </div>
            <p
              style={{
                flex: 1,
                minWidth: "200px",
                color: "var(--text-soft)",
                fontSize: "0.9rem",
                lineHeight: 1.6,
                paddingTop: "0.5rem",
              }}
            >
              Stroop is the canonical style reference for the treat family. Friendly cartoon
              character, big shiny eyes, rosy cheeks, clean vector feel with slight shading. The
              treats follow the same approach: simple shapes, expressive faces, no text in the
              image.
            </p>
          </div>
        </Section>

        {/* Palette comparison */}
        <Section title="Palette Proposals">
          <p
            style={{
              color: "var(--text-soft)",
              marginBottom: "1.5rem",
              fontSize: "0.9rem",
            }}
          >
            Three complete token sets. Each scopes under a{" "}
            <code
              style={{
                background: "var(--surface-card-alt)",
                padding: "0.1em 0.3em",
                borderRadius: "0.25rem",
                fontSize: "0.85em",
              }}
            >
              .palette-*
            </code>{" "}
            wrapper so the live theme is untouched. The CSS files live in{" "}
            <code
              style={{
                background: "var(--surface-card-alt)",
                padding: "0.1em 0.3em",
                borderRadius: "0.25rem",
                fontSize: "0.85em",
              }}
            >
              src/styles/palettes/
            </code>
            .
          </p>
          <div
            data-testid="palette-panels"
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
              gap: "1.5rem",
            }}
          >
            {PALETTES.map((palette) => (
              <PalettePanel key={palette.slug} palette={palette} />
            ))}
          </div>
        </Section>

        {/* CSS animations cheat-sheet */}
        <Section title="Animation Frames">
          <AnimationDemo />
        </Section>
      </div>

      {/* Inline keyframe styles */}
      <StyleguideStyles />
    </main>
  );
}

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: "3rem" }}>
      <h2
        style={{
          fontFamily: "var(--font-display)",
          fontSize: "1.5rem",
          fontWeight: 600,
          color: "var(--text-strong)",
          marginBottom: "1rem",
          paddingBottom: "0.5rem",
          borderBottom: "2px solid var(--line-soft)",
        }}
      >
        {title}
      </h2>
      {children}
    </section>
  );
}

function ExpressionPicker({
  active,
  onChange,
}: {
  active: Expression;
  onChange: (e: Expression) => void;
}) {
  return (
    <div style={{ display: "flex", gap: "0.75rem", flexWrap: "wrap" }}>
      {EXPRESSIONS.map((expr) => (
        <button
          key={expr}
          onClick={() => onChange(expr)}
          style={{
            padding: "0.4rem 1rem",
            borderRadius: "var(--radius-pill)",
            border: "2px solid",
            borderColor: active === expr ? "var(--color-brand-orange)" : "var(--line-soft)",
            background: active === expr ? "var(--color-brand-orange-soft)" : "transparent",
            color: active === expr ? "var(--color-brand-orange-dark)" : "var(--text-soft)",
            fontFamily: "var(--font-display)",
            fontWeight: 600,
            cursor: "pointer",
            textTransform: "capitalize",
          }}
        >
          {expr}
        </button>
      ))}
    </div>
  );
}

/**
 * Cast card — one treat character per the design sheet's `CastCard`.
 * Shows the active-expression hero frame (driven by the picker), the three
 * expression frames, a role pill, tagline, where it appears, and the vocab
 * it brings. Per-character `accent` colour tints the role + vocab chips.
 */
function CastCard({
  treat,
  activeExpression,
}: {
  treat: (typeof TREATS)[number];
  activeExpression: Expression;
}) {
  const animClass =
    activeExpression === "idle"
      ? "anim-idle-bob"
      : activeExpression === "happy"
        ? "anim-happy-bounce"
        : "anim-surprised-pop";

  return (
    <div
      style={{
        background: "var(--surface-card)",
        border: "1.5px solid var(--line-soft)",
        borderRadius: "var(--radius-card)",
        padding: "1.125rem",
        boxShadow: "0 2px 0 0 rgba(0,0,0,.03), 0 12px 28px -16px rgba(0,0,0,.1)",
        position: "relative",
        overflow: "hidden",
      }}
    >
      {/* name + eponym */}
      <div style={{ display: "flex", alignItems: "flex-start", gap: "0.75rem" }}>
        <div style={{ minWidth: 0 }}>
          <div
            style={{
              fontFamily: "var(--font-display)",
              fontWeight: 700,
              fontSize: "1.35rem",
              color: "var(--text-strong)",
              lineHeight: 1.1,
            }}
          >
            {treat.name}
          </div>
          <div
            style={{
              fontSize: "0.75rem",
              color: "var(--text-muted)",
              marginTop: "0.15rem",
            }}
          >
            {treat.eponym}
          </div>
        </div>
        {/* active-expression hero frame — first img in DOM, tracks the picker */}
        <img
          src={`/mascot/treats/${treat.slug}/${activeExpression}.png`}
          alt={`${treat.name} mascot — ${activeExpression}`}
          className={animClass}
          style={{
            width: 64,
            height: 64,
            objectFit: "contain",
            marginLeft: "auto",
            flexShrink: 0,
          }}
        />
      </div>

      {/* three expression frames */}
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(3, 1fr)",
          gap: "0.5rem",
          marginTop: "0.9rem",
          alignItems: "end",
        }}
      >
        {EXPRESSIONS.map((mood) => (
          <div
            key={mood}
            style={{
              background: "var(--surface-card-alt)",
              borderRadius: "0.75rem",
              padding: "0.4rem",
              display: "grid",
              placeItems: "center",
              aspectRatio: "1 / 1",
              border: "1px solid var(--line-soft)",
            }}
          >
            <img
              src={`/mascot/treats/${treat.slug}/${mood}.png`}
              alt={`${treat.name} — ${mood}`}
              style={{ width: 64, height: 64, objectFit: "contain" }}
            />
          </div>
        ))}
      </div>
      <div
        style={{
          display: "grid",
          gridTemplateColumns: "repeat(3, 1fr)",
          gap: "0.5rem",
          marginTop: "0.25rem",
          fontFamily: "var(--font-display)",
          fontWeight: 600,
          fontSize: "0.65rem",
          color: "var(--text-muted)",
          textAlign: "center",
        }}
      >
        <span>idle</span>
        <span>happy</span>
        <span>surprised</span>
      </div>

      {/* role + tagline */}
      <div style={{ marginTop: "0.85rem" }}>
        <span
          style={{
            display: "inline-block",
            fontFamily: "var(--font-display)",
            fontWeight: 700,
            fontSize: "0.625rem",
            letterSpacing: "0.08em",
            textTransform: "uppercase",
            color: treat.accent,
            background: `color-mix(in srgb, ${treat.accent} 14%, transparent)`,
            padding: "0.2rem 0.55rem",
            borderRadius: "var(--radius-pill)",
          }}
        >
          {treat.role}
        </span>
        <p
          style={{
            marginTop: "0.45rem",
            fontSize: "0.825rem",
            color: "var(--text-body)",
            lineHeight: 1.45,
          }}
        >
          {treat.tagline}
        </p>
      </div>

      {/* appears in */}
      <div style={{ marginTop: "0.85rem" }}>
        <div
          style={{
            fontFamily: "var(--font-display)",
            fontWeight: 700,
            fontSize: "0.625rem",
            letterSpacing: "0.08em",
            textTransform: "uppercase",
            color: "var(--text-muted)",
            marginBottom: "0.35rem",
          }}
        >
          Appears in
        </div>
        <div style={{ display: "flex", flexWrap: "wrap", gap: "0.3rem" }}>
          {treat.uses.map((u) => (
            <span
              key={u}
              style={{
                fontFamily: "var(--font-display)",
                fontWeight: 600,
                fontSize: "0.7rem",
                color: "var(--text-soft)",
                background: "var(--surface-card-alt)",
                padding: "0.2rem 0.5rem",
                borderRadius: "0.5rem",
                border: "1px solid var(--line-soft)",
              }}
            >
              {u}
            </span>
          ))}
        </div>
      </div>

      {/* brings vocab */}
      <div style={{ marginTop: "0.7rem" }}>
        <div
          style={{
            fontFamily: "var(--font-display)",
            fontWeight: 700,
            fontSize: "0.625rem",
            letterSpacing: "0.08em",
            textTransform: "uppercase",
            color: "var(--text-muted)",
            marginBottom: "0.35rem",
          }}
        >
          Brings vocab
        </div>
        <div style={{ display: "flex", flexWrap: "wrap", gap: "0.3rem" }}>
          {treat.vocab.map((v) => (
            <span
              key={v}
              style={{
                fontFamily: "var(--font-display)",
                fontWeight: 700,
                fontSize: "0.75rem",
                color: treat.accent,
                background: `color-mix(in srgb, ${treat.accent} 12%, transparent)`,
                padding: "0.2rem 0.5rem",
                borderRadius: "0.5rem",
              }}
            >
              {v}
            </span>
          ))}
        </div>
      </div>
    </div>
  );
}

function PalettePanel({ palette }: { palette: (typeof PALETTES)[number] }) {
  return (
    <div
      className={`palette-${palette.slug}`}
      style={{
        borderRadius: "var(--radius-card)",
        border: "1px solid var(--line-soft)",
        overflow: "hidden",
      }}
    >
      {/* Header */}
      <div
        style={{
          background: palette.swatches[0].value,
          padding: "1rem",
          color: "white",
        }}
      >
        <h3
          style={{
            fontFamily: "var(--font-display)",
            fontWeight: 700,
            margin: 0,
            fontSize: "1.2rem",
          }}
        >
          {palette.name}
        </h3>
      </div>

      {/* Body */}
      <div style={{ padding: "1rem", background: "white" }}>
        <p
          style={{
            fontSize: "0.82rem",
            color: "#555",
            marginBottom: "1rem",
            lineHeight: 1.5,
          }}
        >
          {palette.rationale}
        </p>

        {/* Swatches */}
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr",
            gap: "0.5rem",
            marginBottom: "1rem",
          }}
        >
          {palette.swatches.map((swatch) => (
            <div key={swatch.label} style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
              <div
                style={{
                  width: 28,
                  height: 28,
                  borderRadius: "0.375rem",
                  background: swatch.value,
                  border: "1px solid rgba(0,0,0,0.1)",
                  flexShrink: 0,
                }}
              />
              <div>
                <div style={{ fontSize: "0.7rem", color: "#888", lineHeight: 1.2 }}>
                  {swatch.label}
                </div>
                <div
                  style={{ fontSize: "0.7rem", fontFamily: "monospace", color: "#444" }}
                >
                  {swatch.value}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Sample components */}
        <div style={{ marginTop: "1rem" }}>
          <p style={{ fontSize: "0.75rem", color: "#888", marginBottom: "0.5rem" }}>
            Sample components
          </p>
          {/* Button */}
          <button
            style={{
              background: palette.swatches[0].value,
              color: "white",
              border: "none",
              borderRadius: "0.75rem",
              padding: "0.5rem 1.25rem",
              fontFamily: "var(--font-display)",
              fontWeight: 600,
              fontSize: "0.9rem",
              cursor: "pointer",
              boxShadow: `0 3px 0 0 ${palette.swatches[1].value}`,
              marginBottom: "0.75rem",
              display: "block",
            }}
          >
            Start learning
          </button>

          {/* Card */}
          <div
            style={{
              background: palette.swatches[3].value,
              borderRadius: "0.75rem",
              padding: "0.75rem",
              border: `1px solid ${palette.swatches[0].value}22`,
              fontSize: "0.8rem",
            }}
          >
            <div
              style={{
                fontFamily: "var(--font-display)",
                fontWeight: 600,
                color: palette.swatches[1].value,
                marginBottom: "0.25rem",
              }}
            >
              Drill card
            </div>
            <div style={{ color: "#555" }}>
              What is the Dutch word for{" "}
              <strong style={{ color: palette.swatches[0].value }}>apple</strong>?
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function AnimationDemo() {
  return (
    <div
      style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
        gap: "1rem",
      }}
    >
      {[
        {
          name: "Idle bob",
          className: "anim-idle-bob",
          desc: "Gentle 2px vertical bob on a 2.5 s ease loop. Use for resting mascot.",
        },
        {
          name: "Happy bounce",
          className: "anim-happy-bounce",
          desc: "Big 10px bounce with slight squash, 0.5 s duration. Use for correct answer.",
        },
        {
          name: "Surprised pop",
          className: "anim-surprised-pop",
          desc: "Scale 1 → 1.2 → 1, 0.3 s ease. Use for wrong answer or reveal.",
        },
      ].map((anim) => (
        <div
          key={anim.className}
          style={{
            background: "white",
            borderRadius: "var(--radius-card)",
            padding: "1.25rem",
            border: "1px solid var(--line-soft)",
            textAlign: "center",
          }}
        >
          <img
            src="/mascot/stroop-512.png"
            alt={`${anim.name} animation demo`}
            className={anim.className}
            style={{ width: 72, height: 72, objectFit: "contain" }}
          />
          <p
            style={{
              fontFamily: "var(--font-display)",
              fontWeight: 600,
              margin: "0.5rem 0 0.25rem",
              color: "var(--text-strong)",
            }}
          >
            {anim.name}
          </p>
          <p style={{ fontSize: "0.75rem", color: "var(--text-muted)", margin: 0, lineHeight: 1.4 }}>
            {anim.desc}
          </p>
          <code
            style={{
              display: "block",
              marginTop: "0.5rem",
              fontSize: "0.7rem",
              color: "var(--color-brand-blue)",
              background: "var(--color-brand-blue-soft)",
              padding: "0.2em 0.5em",
              borderRadius: "0.25rem",
            }}
          >
            .{anim.className}
          </code>
        </div>
      ))}
    </div>
  );
}

function StyleguideStyles() {
  return (
    <style>{`
      @keyframes idle-bob {
        0%, 100% { transform: translateY(0); }
        50% { transform: translateY(-2px); }
      }
      @keyframes happy-bounce {
        0% { transform: translateY(0) scaleY(1) scaleX(1); }
        30% { transform: translateY(-10px) scaleY(1.05) scaleX(0.95); }
        60% { transform: translateY(0) scaleY(0.95) scaleX(1.05); }
        80% { transform: translateY(-4px) scaleY(1.02) scaleX(0.98); }
        100% { transform: translateY(0) scaleY(1) scaleX(1); }
      }
      @keyframes surprised-pop {
        0% { transform: scale(1); }
        40% { transform: scale(1.2); }
        70% { transform: scale(0.95); }
        100% { transform: scale(1); }
      }

      .anim-idle-bob {
        animation: idle-bob 2.5s ease-in-out infinite;
      }
      .anim-happy-bounce {
        animation: happy-bounce 0.5s ease-in-out infinite;
      }
      .anim-surprised-pop {
        animation: surprised-pop 0.3s ease-in-out infinite;
      }
    `}</style>
  );
}
