/**
 * /styleguide — branding showcase
 *
 * Dev-only route. Gated at the loader level via `import.meta.env.DEV`.
 * Vite statically replaces that with `false` in production builds, so
 * the redirect branch is dead-code-eliminated and the route becomes an
 * unreachable stub in the deployed worker.
 *
 * Shows:
 *   1. The Dutch-treat mascot family with idle / happy / surprised
 *      expression frames and CSS keyframe animations.
 *   2. Three palette proposals side-by-side: candy, warm-bakery, vibrant.
 *      Each is scoped under a `.palette-<name>` wrapper class so the
 *      live tokens in src/styles.css are never touched.
 *
 * Generated by GH issue #186.
 */
import { createFileRoute, redirect } from "@tanstack/react-router";
import { useState } from "react";

// ---------------------------------------------------------------------------
// Data
// ---------------------------------------------------------------------------

const TREATS = [
  {
    slug: "kroket",
    name: "Kroket",
    emoji: "🥩",
    description: "Golden-brown croquette. Crispy outside, creamy inside.",
  },
  {
    slug: "bitterballen",
    name: "Bitterballen",
    emoji: "🔵",
    description: "Round fried snacks. A Dutch bar staple.",
  },
  {
    slug: "oliebollen",
    name: "Oliebollen",
    emoji: "🍩",
    description: "Deep-fried dough balls. New Year's Eve tradition.",
  },
  {
    slug: "drop",
    name: "Drop",
    emoji: "⬛",
    description: "Black licorice. Salty or sweet — fiercely divisive.",
  },
  {
    slug: "poffertjes",
    name: "Poffertjes",
    emoji: "🥞",
    description: "Mini puffy pancakes. Dusted with powdered sugar.",
  },
  {
    slug: "frikandel",
    name: "Frikandel",
    emoji: "🌭",
    description: "Fried minced-meat sausage. Snack-bar classic.",
  },
  {
    slug: "tompouce",
    name: "Tompouce",
    emoji: "🟥",
    description: "Layered pastry with pink fondant top. Bakkerij staple.",
  },
  {
    slug: "kaas",
    name: "Kaas",
    emoji: "🧀",
    description: "Gouda cheese wedge. The Netherlands' greatest export.",
  },
] as const;

const EXPRESSIONS = ["idle", "happy", "surprised"] as const;
type Expression = (typeof EXPRESSIONS)[number];

const PALETTES = [
  {
    slug: "candy",
    name: "Candy",
    rationale:
      "Vivid pinks, electric purples, citrus yellows. Inspired by Dutch hagelslag and sweet-shop treats. Suits a younger audience or seasonal promotions.",
    swatches: [
      { label: "Brand primary", value: "#FF3E9A" },
      { label: "Brand primary dark", value: "#C4006E" },
      { label: "Brand accent", value: "#7B2FFF" },
      { label: "Paper bg", value: "#FFF5FB" },
      { label: "Good", value: "#2DBE6C" },
      { label: "Bad", value: "#FF2D55" },
    ],
  },
  {
    slug: "warm-bakery",
    name: "Warm Bakery",
    rationale:
      "Terracotta brand colour, dark rye ink, parchment surfaces. Inspired by Dutch bakkerij interiors. Feels trustworthy and nostalgic without being heavy.",
    swatches: [
      { label: "Brand primary", value: "#D4600A" },
      { label: "Brand primary dark", value: "#9E4200" },
      { label: "Brand accent", value: "#5A6E2E" },
      { label: "Paper bg", value: "#FDF6EC" },
      { label: "Good", value: "#4A8A3A" },
      { label: "Bad", value: "#A83030" },
    ],
  },
  {
    slug: "vibrant",
    name: "Vibrant",
    rationale:
      "Electric teal + Dutch orange at maximum saturation. The Duolingo-green equivalent for Lekkertaal. Loud, gamified, fast. Suits a future dark-mode-first variant.",
    swatches: [
      { label: "Brand primary", value: "#FF5500" },
      { label: "Brand primary dark", value: "#CC3A00" },
      { label: "Brand accent", value: "#00A8CC" },
      { label: "Paper bg", value: "#F5FEFF" },
      { label: "Good", value: "#00CC66" },
      { label: "Bad", value: "#FF2244" },
    ],
  },
] as const;

// ---------------------------------------------------------------------------
// Route
// ---------------------------------------------------------------------------

export const Route = createFileRoute("/styleguide")({
  loader: async () => {
    // Dead-code-eliminated in prod builds — the redirect becomes unreachable.
    if (!import.meta.env.DEV) {
      throw redirect({ to: "/" });
    }
    return null;
  },
  component: StyleguidePage,
});

// ---------------------------------------------------------------------------
// Components
// ---------------------------------------------------------------------------

function StyleguidePage() {
  const [activeExpression, setActiveExpression] = useState<Expression>("idle");

  return (
    <main
      style={{
        minHeight: "100vh",
        background: "var(--surface-page)",
        fontFamily: "var(--font-sans)",
        padding: "2rem 1.5rem 4rem",
      }}
    >
      <div style={{ maxWidth: "72rem", margin: "0 auto" }}>
        {/* Header */}
        <header style={{ textAlign: "center", marginBottom: "3rem" }}>
          <h1
            style={{
              fontFamily: "var(--font-display)",
              fontSize: "2.5rem",
              fontWeight: 700,
              margin: 0,
            }}
          >
            <span style={{ color: "var(--color-brand-orange)" }}>Lekker</span>
            <span style={{ color: "var(--color-brand-blue)" }}>taal</span>{" "}
            <span style={{ color: "var(--text-soft)" }}>Styleguide</span>
          </h1>
          <p
            style={{
              marginTop: "0.5rem",
              color: "var(--text-muted)",
              fontSize: "0.9rem",
            }}
          >
            Dev-only. Dutch-treat mascots + palette proposals. GH{" "}
            <a
              href="https://github.com/RonanCodes/lekkertaal/issues/186"
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: "var(--color-brand-blue)" }}
            >
              #186
            </a>
            . Research{" "}
            <a
              href="https://github.com/RonanCodes/lekkertaal/issues/184"
              target="_blank"
              rel="noopener noreferrer"
              style={{ color: "var(--color-brand-blue)" }}
            >
              #184
            </a>
            .
          </p>
        </header>

        {/* Mascot gallery */}
        <Section title="Treat Mascot Family">
          <ExpressionPicker active={activeExpression} onChange={setActiveExpression} />
          <div
            data-testid="treat-gallery"
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fill, minmax(160px, 1fr))",
              gap: "1.5rem",
              marginTop: "1.5rem",
            }}
          >
            {TREATS.map((treat) => (
              <TreatCard key={treat.slug} treat={treat} expression={activeExpression} />
            ))}
          </div>
        </Section>

        {/* Stroop included for style reference */}
        <Section title="Style Reference: Stroop">
          <div
            style={{
              display: "flex",
              gap: "1.5rem",
              flexWrap: "wrap",
              alignItems: "flex-start",
            }}
          >
            <div style={{ textAlign: "center" }}>
              <img
                src="/mascot/stroop-512.png"
                alt="Stroop the stroopwafel — existing mascot"
                style={{
                  width: 128,
                  height: 128,
                  objectFit: "contain",
                  borderRadius: "var(--radius-card)",
                  background: "white",
                  padding: "0.5rem",
                  border: "1px solid var(--line-soft)",
                }}
              />
              <p
                style={{
                  marginTop: "0.5rem",
                  fontSize: "0.8rem",
                  color: "var(--text-muted)",
                }}
              >
                Stroop (existing)
              </p>
            </div>
            <p
              style={{
                flex: 1,
                minWidth: "200px",
                color: "var(--text-soft)",
                fontSize: "0.9rem",
                lineHeight: 1.6,
                paddingTop: "0.5rem",
              }}
            >
              Stroop is the canonical style reference for the treat family. Friendly cartoon
              character, big shiny eyes, rosy cheeks, clean vector feel with slight shading. The
              treats follow the same approach: simple shapes, expressive faces, no text in the
              image.
            </p>
          </div>
        </Section>

        {/* Palette comparison */}
        <Section title="Palette Proposals">
          <p
            style={{
              color: "var(--text-soft)",
              marginBottom: "1.5rem",
              fontSize: "0.9rem",
            }}
          >
            Three complete token sets. Each scopes under a{" "}
            <code
              style={{
                background: "var(--surface-card-alt)",
                padding: "0.1em 0.3em",
                borderRadius: "0.25rem",
                fontSize: "0.85em",
              }}
            >
              .palette-*
            </code>{" "}
            wrapper so the live theme is untouched. The CSS files live in{" "}
            <code
              style={{
                background: "var(--surface-card-alt)",
                padding: "0.1em 0.3em",
                borderRadius: "0.25rem",
                fontSize: "0.85em",
              }}
            >
              src/styles/palettes/
            </code>
            .
          </p>
          <div
            data-testid="palette-panels"
            style={{
              display: "grid",
              gridTemplateColumns: "repeat(auto-fit, minmax(300px, 1fr))",
              gap: "1.5rem",
            }}
          >
            {PALETTES.map((palette) => (
              <PalettePanel key={palette.slug} palette={palette} />
            ))}
          </div>
        </Section>

        {/* CSS animations cheat-sheet */}
        <Section title="Animation Frames">
          <AnimationDemo />
        </Section>
      </div>

      {/* Inline keyframe styles */}
      <StyleguideStyles />
    </main>
  );
}

// ---------------------------------------------------------------------------
// Sub-components
// ---------------------------------------------------------------------------

function Section({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <section style={{ marginBottom: "3rem" }}>
      <h2
        style={{
          fontFamily: "var(--font-display)",
          fontSize: "1.5rem",
          fontWeight: 600,
          color: "var(--text-strong)",
          marginBottom: "1rem",
          paddingBottom: "0.5rem",
          borderBottom: "2px solid var(--line-soft)",
        }}
      >
        {title}
      </h2>
      {children}
    </section>
  );
}

function ExpressionPicker({
  active,
  onChange,
}: {
  active: Expression;
  onChange: (e: Expression) => void;
}) {
  return (
    <div style={{ display: "flex", gap: "0.75rem", flexWrap: "wrap" }}>
      {EXPRESSIONS.map((expr) => (
        <button
          key={expr}
          onClick={() => onChange(expr)}
          style={{
            padding: "0.4rem 1rem",
            borderRadius: "var(--radius-pill)",
            border: "2px solid",
            borderColor: active === expr ? "var(--color-brand-orange)" : "var(--line-soft)",
            background: active === expr ? "var(--color-brand-orange-soft)" : "transparent",
            color: active === expr ? "var(--color-brand-orange-dark)" : "var(--text-soft)",
            fontFamily: "var(--font-display)",
            fontWeight: 600,
            cursor: "pointer",
            textTransform: "capitalize",
          }}
        >
          {expr}
        </button>
      ))}
    </div>
  );
}

function TreatCard({
  treat,
  expression,
}: {
  treat: (typeof TREATS)[number];
  expression: Expression;
}) {
  const animClass = expression === "idle" ? "anim-idle-bob" : expression === "happy" ? "anim-happy-bounce" : "anim-surprised-pop";

  return (
    <div
      style={{
        background: "white",
        borderRadius: "var(--radius-card)",
        padding: "1rem",
        border: "1px solid var(--line-soft)",
        textAlign: "center",
        boxShadow: "0 2px 8px rgba(0,0,0,0.05)",
      }}
    >
      <div style={{ display: "flex", justifyContent: "center", marginBottom: "0.5rem" }}>
        <img
          src={`/mascot/treats/${treat.slug}/${expression}.png`}
          alt={`${treat.name} mascot — ${expression}`}
          className={animClass}
          style={{
            width: 100,
            height: 100,
            objectFit: "contain",
          }}
        />
      </div>
      <p
        style={{
          fontFamily: "var(--font-display)",
          fontWeight: 600,
          fontSize: "1rem",
          margin: "0 0 0.25rem",
          color: "var(--text-strong)",
        }}
      >
        {treat.emoji} {treat.name}
      </p>
      <p
        style={{
          fontSize: "0.75rem",
          color: "var(--text-muted)",
          margin: 0,
          lineHeight: 1.4,
        }}
      >
        {treat.description}
      </p>
    </div>
  );
}

function PalettePanel({ palette }: { palette: (typeof PALETTES)[number] }) {
  return (
    <div
      className={`palette-${palette.slug}`}
      style={{
        borderRadius: "var(--radius-card)",
        border: "1px solid var(--line-soft)",
        overflow: "hidden",
      }}
    >
      {/* Header */}
      <div
        style={{
          background: palette.swatches[0].value,
          padding: "1rem",
          color: "white",
        }}
      >
        <h3
          style={{
            fontFamily: "var(--font-display)",
            fontWeight: 700,
            margin: 0,
            fontSize: "1.2rem",
          }}
        >
          {palette.name}
        </h3>
      </div>

      {/* Body */}
      <div style={{ padding: "1rem", background: "white" }}>
        <p
          style={{
            fontSize: "0.82rem",
            color: "#555",
            marginBottom: "1rem",
            lineHeight: 1.5,
          }}
        >
          {palette.rationale}
        </p>

        {/* Swatches */}
        <div
          style={{
            display: "grid",
            gridTemplateColumns: "1fr 1fr",
            gap: "0.5rem",
            marginBottom: "1rem",
          }}
        >
          {palette.swatches.map((swatch) => (
            <div key={swatch.label} style={{ display: "flex", alignItems: "center", gap: "0.5rem" }}>
              <div
                style={{
                  width: 28,
                  height: 28,
                  borderRadius: "0.375rem",
                  background: swatch.value,
                  border: "1px solid rgba(0,0,0,0.1)",
                  flexShrink: 0,
                }}
              />
              <div>
                <div style={{ fontSize: "0.7rem", color: "#888", lineHeight: 1.2 }}>
                  {swatch.label}
                </div>
                <div
                  style={{ fontSize: "0.7rem", fontFamily: "monospace", color: "#444" }}
                >
                  {swatch.value}
                </div>
              </div>
            </div>
          ))}
        </div>

        {/* Sample components */}
        <div style={{ marginTop: "1rem" }}>
          <p style={{ fontSize: "0.75rem", color: "#888", marginBottom: "0.5rem" }}>
            Sample components
          </p>
          {/* Button */}
          <button
            style={{
              background: palette.swatches[0].value,
              color: "white",
              border: "none",
              borderRadius: "0.75rem",
              padding: "0.5rem 1.25rem",
              fontFamily: "var(--font-display)",
              fontWeight: 600,
              fontSize: "0.9rem",
              cursor: "pointer",
              boxShadow: `0 3px 0 0 ${palette.swatches[1].value}`,
              marginBottom: "0.75rem",
              display: "block",
            }}
          >
            Start learning
          </button>

          {/* Card */}
          <div
            style={{
              background: palette.swatches[3].value,
              borderRadius: "0.75rem",
              padding: "0.75rem",
              border: `1px solid ${palette.swatches[0].value}22`,
              fontSize: "0.8rem",
            }}
          >
            <div
              style={{
                fontFamily: "var(--font-display)",
                fontWeight: 600,
                color: palette.swatches[1].value,
                marginBottom: "0.25rem",
              }}
            >
              Drill card
            </div>
            <div style={{ color: "#555" }}>
              What is the Dutch word for{" "}
              <strong style={{ color: palette.swatches[0].value }}>apple</strong>?
            </div>
          </div>
        </div>
      </div>
    </div>
  );
}

function AnimationDemo() {
  return (
    <div
      style={{
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
        gap: "1rem",
      }}
    >
      {[
        {
          name: "Idle bob",
          className: "anim-idle-bob",
          desc: "Gentle 2px vertical bob on a 2.5 s ease loop. Use for resting mascot.",
        },
        {
          name: "Happy bounce",
          className: "anim-happy-bounce",
          desc: "Big 10px bounce with slight squash, 0.5 s duration. Use for correct answer.",
        },
        {
          name: "Surprised pop",
          className: "anim-surprised-pop",
          desc: "Scale 1 → 1.2 → 1, 0.3 s ease. Use for wrong answer or reveal.",
        },
      ].map((anim) => (
        <div
          key={anim.className}
          style={{
            background: "white",
            borderRadius: "var(--radius-card)",
            padding: "1.25rem",
            border: "1px solid var(--line-soft)",
            textAlign: "center",
          }}
        >
          <img
            src="/mascot/stroop-512.png"
            alt={`${anim.name} animation demo`}
            className={anim.className}
            style={{ width: 72, height: 72, objectFit: "contain" }}
          />
          <p
            style={{
              fontFamily: "var(--font-display)",
              fontWeight: 600,
              margin: "0.5rem 0 0.25rem",
              color: "var(--text-strong)",
            }}
          >
            {anim.name}
          </p>
          <p style={{ fontSize: "0.75rem", color: "var(--text-muted)", margin: 0, lineHeight: 1.4 }}>
            {anim.desc}
          </p>
          <code
            style={{
              display: "block",
              marginTop: "0.5rem",
              fontSize: "0.7rem",
              color: "var(--color-brand-blue)",
              background: "var(--color-brand-blue-soft)",
              padding: "0.2em 0.5em",
              borderRadius: "0.25rem",
            }}
          >
            .{anim.className}
          </code>
        </div>
      ))}
    </div>
  );
}

function StyleguideStyles() {
  return (
    <style>{`
      @keyframes idle-bob {
        0%, 100% { transform: translateY(0); }
        50% { transform: translateY(-2px); }
      }
      @keyframes happy-bounce {
        0% { transform: translateY(0) scaleY(1) scaleX(1); }
        30% { transform: translateY(-10px) scaleY(1.05) scaleX(0.95); }
        60% { transform: translateY(0) scaleY(0.95) scaleX(1.05); }
        80% { transform: translateY(-4px) scaleY(1.02) scaleX(0.98); }
        100% { transform: translateY(0) scaleY(1) scaleX(1); }
      }
      @keyframes surprised-pop {
        0% { transform: scale(1); }
        40% { transform: scale(1.2); }
        70% { transform: scale(0.95); }
        100% { transform: scale(1); }
      }

      .anim-idle-bob {
        animation: idle-bob 2.5s ease-in-out infinite;
      }
      .anim-happy-bounce {
        animation: happy-bounce 0.5s ease-in-out infinite;
      }
      .anim-surprised-pop {
        animation: surprised-pop 0.3s ease-in-out infinite;
      }
    `}</style>
  );
}
